### ISSUE TITLE
Make getting started document

### ISSUE THREAD

**Issue by LTamara1013** [knezicm/sava-drina#20]
Napraviti Wiki stranicu u kojoj će se nalaziti svi neophodni koraci za instaliranje i konfiguraciju VUnit frameworka, kao i koraci za pravljenje i pokretanje testova.

**Comment by JovanaAre** [comment]
Procijenjeno vrijeme za izradu zadatka je 3h.

**Comment by JovanaAre** [comment]
Aktivnosti sprovedene na izradi zadatka:
- Konfiguracija VUnit framework-a na računaru
- Čitanje o VUnit framework-u iz različitih izvora
- Objedinjavanje stečenih znanja u jedinstven wiki dokument
